import java.util.Random;

public class BancoDePalavras {

    public String palavraAleatoria() {

        String [] listaPalavras = {
                "aventura", "borboleta", "relogios", "maratona", "nebulosa", "granito", "horizonte", "oceanico", "castanho", "formiguei", "bicicletas", "diamante", "florestas", "serpente", "guerreiro", "pandorga", "melancia", "xadrezes", "triatlon", "embarcar", "girassol", "abismoide", "magistral", "corromper", "transito", "serpentes", "vitralha", "piramide", "golfinho", "fragrante", "nordeste", "marisqueo", "planetas", "satelite", "sobrenviv", "reliquias", "historiar", "pinturao", "orquidea", "sinfonia", "camarotes", "algoritmos", "nebulizar", "triangulo", "espirais", "navegante", "migracao", "escultor", "colmeias", "galaxias", "literatura", "amizades", "paralelo", "estampado", "frutificar", "adormeci", "borbulhar", "carpintei", "dominante", "silencios", "roldanas", "acrobatas", "mensageiro", "desbravar",
                "alfaiate", "protetor", "molduras", "quebravél", "cafezal", "tempestes", "nitrogens", "rodoviaro", "reviravol", "esfingica", "costelada", "alvoradas", "campestre", "litoranea", "foguetes", "mascarado", "imaginado", "turbinas", "planetario", "borrachei", "luminosos", "oceaniado", "cronometo", "trianglar", "auditiva", "estaciona", "torneiras", "aventurei", "picoleira", "carpintar", "ilusionar", "estalagem", "esvoacar", "barqueiro", "marinheiro", "passarela", "dominante", "navegacao", "portuaria", "artesanato", "cozinheiro", "laranjeira", "hectarees", "madeirais", "estantear", "giratorias", "generosos", "luminosas", "fulgurante", "inventivo", "tartaruga", "crocodilo", "dentritas", "parabolas", "mirabolan", "orvalhoes", "musculoso", "aeromotor", "heliponto", "montanhaz", "escalador", "pedregoso",
                "folhagens", "floreados", "espadarte", "cangaceiro", "estrangei", "academico", "pastoreio", "linguista", "arqueiros", "imaginado", "fragancia", "laborioso", "requintar", "desperdil", "majestade", "autoralha", "rodopiante", "narrativo", "empanadas", "chalaneiro", "violetado", "enigmatico", "sortilego", "dicionario", "hibernado", "chocolate", "fragmento", "artesanais", "ventanias", "sussurros", "noturnal", "cintilante", "carpideira", "curvatura", "ascensao", "despertao", "horizonte", "destemido", "flamengos", "alvoracao", "lanternas", "paneladas", "navieiros", "mergulho", "mergulhar", "retroceso", "caminhado", "galinheiro", "bravatear", "relampejo", "escarlate", "mandacaru", "cintilado", "celebrada", "patinador", "agricultor", "estadista", "luminosos", "arcadismo", "temporalha", "genericos", "biodivers",
                "vinagrete", "calculado", "inflamado", "misturado", "esquentar", "congelado", "ambulante", "remakeado", "codifiquei", "floricult", "romantico", "sombreamo", "petroleos", "vestibulo", "amedrontar", "tecelagem", "envernizar", "carpintaria", "colecionar", "campeonatos", "eletricista", "mergulhador", "lanternagem", "armazenado", "embarcacao", "jiboiasse", "maracujas", "pandemonio", "colossais", "ancestral", "misticismo", "melodrama", "guardador", "inspirador", "gravitacao", "lancamento", "escudeiro", "serenatas", "cavalheiro", "meteorito", "pedaleiros", "transbordo", "soberanos", "burguesia", "espantalho", "arvoredo", "toboganas", "rebanhados", "liquidacao", "aquecimento", "suprimentos", "relatancia", "navegantes", "mugidoiro", "benfeitores", "saborizantes", "afetuosos", "contemplar", "ilusionista",
                "replicavel", "montanhoso", "lagostinha", "giramentos", "musculares", "escalonada", "oceaniadas", "barulhenta", "aeroviaria", "mercantil", "borbulhante", "respingado", "vaporizar", "nucleares", "harmonioso", "golpistas", "escaravelho", "temporalidade", "luminosidade", "aventurar", "pacotinhos", "instrumentar", "trilhadores", "majestosos", "horizontear", "incansavel", "pedregulhos", "savanicas", "aquarelista", "manufatura", "interrogado", "despertei", "adocicados", "resignado", "cilindrico", "travessias", "cabrestante", "inventario", "odorizador", "flamboyant", "veludosos", "cronometros", "borrifador", "manivelado", "sacerdotes", "estalactite", "envernizado", "florestal", "alimentado", "predilecao", "caprichosa", "intrepidos", "valentonas"
        };

        Random random = new Random();

        return listaPalavras[random.nextInt(listaPalavras.length)];
    }
}
